### Search
GET http://localhost:3000/search-results?fromLocation=IP3+0QU&toLocation=IP8+3SU
### Search2
GET http://localhost:3000/search-results?fromLocation=IP8+3SU&toLocation=IP8+3SU

### Bad Search
GET http://localhost:3000/search-results?fromLocation=IP+0QU&toLocation=QQQQQQ
### Missing Parameters
GET http://localhost:3000/search-results
